export const FETCH_CHARACTER = 'FETCH_CHARACTER';
export const FETCH_HOUSE = 'FETCH_HOUSE';

export const SELECT_CHARACTER = 'SELECT_CHARACTER';
export const REMOVE_CHARACTER = 'REMOVE_CHARACTER';
export const START_ROLLING_DICE = 'START_ROLLING_DICE';
export const STOP_ROLLING_DICE = 'STOP_ROLLING_DICE';
export const MOVE_TOKEN = 'MOVE_TOKEN';
export const PLAYER_TRAPPED = 'PLAYER_TRAPPED';
export const PLAYER_RETURN = 'PLAYER_RETURN';
export const SET_WINNER = 'SET_WINNER';
