export const FETCH_CHARACTER = 'FETCH_CHARACTER';
export const FETCH_HOUSE = 'FETCH_HOUSE';

export const SELECT_CHARACTER = 'SELECT_CHARACTER';
export const REMOVE_CHARACTER = 'REMOVE_CHARACTER';
export const DICE_ROLLING = 'DICE_ROLLING';
export const SET_CURRENT_PLAYER = 'SET_CURRENT_PLAYER';
export const REGISTER_PLAYER_TOKEN = 'REGISTER_PLAYER_TOKEN';
export const ADD_MOVES_TO_PLAYER = 'ADD_MOVES_TO_PLAYER';
export const MOVE_TOKEN = 'MOVE_TOKEN';
export const SET_PLAYER_TRAPPED = 'SET_PLAYER_TRAPPED';
export const PLAYER_RETURN = 'PLAYER_RETURN';
export const SET_WINNER = 'SET_WINNER';
